import json
import csv
import os
import re
import datetime

# 1. Load authoritative typed JSON
src_json_path = 'rtx_g4_smoke_v5/03_dashboards/docs/audit/02_evidence_rows.json'
with open(src_json_path, 'r', encoding='utf-8') as f:
    full_data = json.load(f)

meta = full_data['meta']
rows = full_data['rows']
missing = full_data['missing_configured_cases']

print(f"Loaded {len(rows)} typed rows and {len(missing)} missing configured cases.")

# Step 0: Extend with fields from vllm_runs.csv joined on (case, bench)
vllm_csv_path = 'rtx_g4_smoke_v5/v6_suite/results/vllm_runs.csv'
with open(vllm_csv_path, 'r', encoding='utf-8') as f:
    vllm_rows = list(csv.DictReader(f))

vllm_map = {(r['case'], r['bench']): r for r in vllm_rows}

for r in rows:
    key = (r['case'], r['bench'])
    if key not in vllm_map:
        raise KeyError(f"Missing row in vllm_runs.csv for {key}")
    vr = vllm_map[key]
    r['metric_samples'] = int(vr['metric_samples'])
    r['completed'] = int(vr['completed'])
    r['preemptions_delta'] = float(vr['preemptions_delta'])
    r['queue_mean_s_from_hist'] = float(vr['queue_mean_s_from_hist'])
    r['source_file'] = 'vllm_runs.csv'
    # Keep provenance_status unchanged (NOT raw-validated: this is a results CSV, not raw logs)

# 2. Type validation assertions
numeric_fields = ['tp', 'pp', 'input_tokens_displayed', 'concurrency', 'ttft_ms', 'tpot_ms', 'output_tok_s', 'kv_peak_pct', 'metric_samples', 'completed', 'preemptions_delta', 'queue_mean_s_from_hist']
for idx, r in enumerate(rows):
    for nf in numeric_fields:
        val = r[nf]
        if not isinstance(val, (int, float)):
            raise TypeError(f"Row {idx} ({r['row_id']}) field '{nf}' is not a number: {val} ({type(val)})")
    if r['run_id'] is not None:
        raise ValueError(f"Row {idx} run_id must be null: {r['run_id']}")
    if r['source_file'] != 'vllm_runs.csv':
        raise ValueError(f"Row {idx} source_file must be 'vllm_runs.csv': {r['source_file']}")
    if r['sample_count_N'] is not None:
        raise ValueError(f"Row {idx} sample_count_N must be null: {r['sample_count_N']}")
    if not isinstance(r['extra_vs_archived_v6'], bool):
        raise TypeError(f"Row {idx} extra_vs_archived_v6 must be boolean: {r['extra_vs_archived_v6']}")

print("All 59 rows passed strict type validation (all numeric fields are numbers, source_file='vllm_runs.csv', absent run_id/sample_count_N are null, flags are booleans).")

# 3. Save data/evidence.json
os.makedirs('data', exist_ok=True)
dest_json_path = 'data/evidence.json'
with open(dest_json_path, 'w', encoding='utf-8') as f:
    json.dump(full_data, f, indent=2)
print(f"Saved {dest_json_path}")

# 4. Generate dynamic build timestamp
build_date = datetime.datetime.now().strftime("%d %b %Y %H:%M")

# 5. Read MASTER_CHARACTERIZATION_DASHBOARD.html and regenerate data block & header
dashboard_path = 'MASTER_CHARACTERIZATION_DASHBOARD.html'
with open(dashboard_path, 'r', encoding='utf-8') as f:
    html = f.read()

# Build evidence script string
evidence_json_str = json.dumps(rows, indent=2)
missing_json_str = json.dumps(missing, indent=2)
meta_json_str = json.dumps(meta, indent=2)

embedded_block = f"""// Authoritative Evidence Data Layer (Generated by tools/build_evidence.py)
const EVIDENCE_META = {meta_json_str};
const EVIDENCE_DATA = {evidence_json_str};
const MISSING_CONFIGURED_CASES = {missing_json_str};

// Runtime type verification check
(function verifyEvidenceDataTypes() {{
  const numFields = ['tp', 'pp', 'input_tokens_displayed', 'concurrency', 'ttft_ms', 'tpot_ms', 'output_tok_s', 'kv_peak_pct', 'metric_samples', 'completed', 'preemptions_delta', 'queue_mean_s_from_hist'];
  EVIDENCE_DATA.forEach((r, i) => {{
    numFields.forEach(f => {{
      if (typeof r[f] !== 'number') {{
        console.error(`Evidence row ${{i}} (${{r.row_id}}) field ${{f}} is not number:`, r[f]);
      }}
    }});
    if (r.source_file !== 'vllm_runs.csv') {{
      console.error(`Evidence row ${{i}} source_file must be vllm_runs.csv:`, r.source_file);
    }}
  }});
  console.log('EVIDENCE_DATA: 59 rows loaded with verified numeric types and source_file=vllm_runs.csv.');
}})();

// Scale-Out Dataset (Current UI values pending raw production validation)
const SCALE_OUT_DATA = [
  {{ topology: 'TP4 / PP4', ttft_128k_ms: 1723.7, tpot_ms: 5.53, output_tok_s: 30.9, traffic_gb_s: 1.2, provenance: 'current UI value pending raw re-validation', evidence_class: 'MEASURED-48B' }},
  {{ topology: 'Forced TP4 / PP2', ttft_128k_ms: 2646.6, tpot_ms: 5.43, output_tok_s: 21.4, traffic_gb_s: 8.6, provenance: 'current UI value pending raw re-validation', evidence_class: 'MEASURED-48B' }},
  {{ topology: 'TP8 / PP2', ttft_128k_ms: 2817.6, tpot_ms: 7.47, output_tok_s: 19.5, traffic_gb_s: 2.4, provenance: 'current UI value pending raw re-validation', evidence_class: 'MEASURED-48B' }},
  {{ topology: 'TP16 / PP1', ttft_128k_ms: 6024.9, tpot_ms: 11.35, output_tok_s: 9.5, traffic_gb_s: 22.4, provenance: 'current UI value pending raw re-validation', evidence_class: 'MEASURED-48B' }}
];

// Helper Query Functions
function getEvidenceRow(caseName, bench) {{
  return EVIDENCE_DATA.find(r => r.case === caseName && r.bench === bench);
}}

function getCaseRows(caseName) {{
  return EVIDENCE_DATA.filter(r => r.case === caseName);
}}
"""

# Replace the data block in script
pattern_block = r"// Authoritative Evidence Data Layer.*?(?=\n// Tab Switching Controller)"
if re.search(pattern_block, html, re.DOTALL):
    html = re.sub(pattern_block, embedded_block.strip(), html, flags=re.DOTALL)
else:
    html = html.replace("<script>", "<script>\n" + embedded_block)

# 6. Update Header timestamps and coverage wording
brand_right_replacement = f"""<div class="brand-right">
    <div class="badge-cluster">
      <span class="pill-badge badge-m"><span class="dot"></span>MEASURED-48B</span>
      <span class="pill-badge badge-gcp"><span class="dot"></span>MEASURED-GCP-HW</span>
      <span class="pill-badge badge-derived"><span class="dot"></span>DERIVED</span>
      <span class="pill-badge badge-local"><span class="dot"></span>LOCAL-REAL</span>
      <span class="pill-badge badge-unres"><span class="dot"></span>UNRESOLVED</span>
    </div>
    <div class="time-live-badge">
      <span>Latest run timestamp: <strong style="color:#fbbf24;">NOT CAPTURED</strong></span>
      <span style="color:#64748b;">|</span>
      <span>Dashboard Built: {build_date}</span>
      <span style="color:#64748b;">|</span>
      <span style="color:#94a3b8;"><span style="display:inline-block; width:6px; height:6px; border-radius:50%; background:#64748b;"></span> Snapshot (Static)</span>
    </div>
    <div style="font-size:8.5px; color:#cbd5e1; display:flex; flex-direction:column; gap:2px; margin-top:2px;">
      <div>
        <span>Suite revision: <strong style="color:#fbbf24;">NOT CAPTURED</strong> (archive name: v6)</span>
        <span style="color:#64748b;">|</span>
        <span>Git SHA: <strong style="color:#fbbf24;">NOT CAPTURED</strong></span>
        <span style="color:#64748b;">|</span>
        <span>Manifest Hash: <strong style="color:#fbbf24;">NOT CAPTURED</strong></span>
      </div>
      <div>
        <span>Coverage: <strong style="color:#34d399;">58 of 64 configured cases present + 1 extra row (tp4_closedloop_1m::c4, not in archived case file) = 59 rows; 6 configured cases absent (3 FP8-KV, 3 native-offload)</strong></span>
      </div>
    </div>
    <div class="disclaimer-sub" style="margin-top:2px;">
      Do not scale absolute 48B surrogate latency to Kimi K3. GCP network results are not local 10GbE measurements. 51/59 rows pending raw production re-validation (qualification 8/8 validated).
    </div>
  </div>"""

html = re.sub(r'<div class="brand-right">.*?</div>\s*</div>\s*<!-- Tab Navigation Bar -->', brand_right_replacement + "\n</div>\n\n<!-- Tab Navigation Bar -->", html, flags=re.DOTALL)

# 7. Add visible UNVERIFIED banner to VRAM doughnut and PCIe charts if not present
banner_css = """
  .unverified-chart-banner { background: #451a03; border: 1px solid #b45309; color: #fde68a; border-radius: 4px; padding: 4px 8px; font-size: 8px; font-weight: 700; margin-bottom: 6px; text-align: center; }
"""
if ".unverified-chart-banner" not in html:
    html = html.replace("</style>", banner_css + "\n</style>")

# Strip any existing banners
html = html.replace('<div class="unverified-chart-banner">⚠️ UNVERIFIED - legacy values, not Blackwell/Gen5 measurements</div>\n      ', '')
html = html.replace('<div class="unverified-chart-banner">⚠️ UNVERIFIED - legacy values, not Blackwell/Gen5 measurements</div>', '')

# Insert cleanly above the canvas in VRAM card and PCIe card
html = html.replace(
    '<div style="height:220px; position:relative;"><canvas id="canvasProfilerVram"></canvas></div>',
    '<div class="unverified-chart-banner">⚠️ UNVERIFIED - legacy values, not Blackwell/Gen5 measurements</div>\n      <div style="height:220px; position:relative;"><canvas id="canvasProfilerVram"></canvas></div>'
)

html = html.replace(
    '<div style="height:220px; position:relative;"><canvas id="canvasProfilerPcie"></canvas></div>',
    '<div class="unverified-chart-banner">⚠️ UNVERIFIED - legacy values, not Blackwell/Gen5 measurements</div>\n      <div style="height:220px; position:relative;"><canvas id="canvasProfilerPcie"></canvas></div>'
)

with open(dashboard_path, 'w', encoding='utf-8') as f:
    f.write(html)

print("Updated MASTER_CHARACTERIZATION_DASHBOARD.html with strictly typed data layer and corrected header wording.")
